### PR TITLE
Feat: Add in an option to use the ajv-formats plugin

### PR DESCRIPTION
**Pull request by VirenMistrys**
Hi vanekj
We have been working on a Workflow that needed an AJV validator to help validate our Yaml files. When searching for AJV actions which could do the job, we stumbled upon yours, which we liked. This action was easy to understand, and we thought it could be the base of what we needed.

With these Actions, we have added a few needed features to make it work within our project and could benefit others looking for the same thing. We have added in:
- An option to use ajv-format plugin. Great for when you use formats not supported by AJV alone.
- An option to allow matching properties. We needed this for our projects because we used "properties" and "patternProperties".
- An option to show validation results in a workflow summary. This is for quick analysis when you want to avoid looking at logs.
- An option allowing you to use referenced schemas within any file type to help validate.
We hope you like the changes we have made.

### CODE REVIEW

**Comment by vanekj** [comment]
Hello @VirenMistrys, I am more than a pleased that somebody is using my package and contributed into it! I will go through the pull request and check on the changes. Thank you 👍🏻

**Comment by VirenMistrys** [comment]
Hey @vanekj. Thank you for getting back to me. There is a last-minute change which I may need to work on. I will let you know when I have added it.

**Comment by VirenMistrys** [comment]
Hey @vanekj.
This is ready to review now. Thank you for holding the review while I fix a few things.

**Comment by VirenMistrys** [comment]
Hey @vanekj.
This PR is ready to be reviewed now. Can I have this review, please?
Thank you.

**Comment by vanekj** [comment]
@VirenMistrys, sorry for the delays, I will review it by this week

**Review by vanekj — APPROVED** [review]

**Comment by vanekj** [comment]
Hi @VirenMistrys, thanks for your submission. I merged the pull-request and will review it locally as well to see if there is some space for refactoring. I should also add some project configurations such as linters, editorconfig, etc.

**Pull request merged**
